name: Codecov CI
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1
      with:
        name: Nota code quality
