name: Example workflow for Codecov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v1
    - name: Upload coverage to Codecov  
      uses: ./
      with:
        name: Nota code quality
